### ISSUE TITLE
New features proposed for openxdagpool

### ISSUE THREAD

**Issue by xrdavies** [XDagger/openxdagpool#1]
New features proposed for openxdagpool:

add a round robin query (on whitelist) to find out which pools are available, and list on website.

And performance of actual mining result, to accompany the proclaimed arguments

This is issue related to openxdagpool moved from xdag repo
@kbs1

**Comment by cnukaus** [comment]
Thanks xddavies, there wasn't "Issues" tab in the pool repo for me so created it in xdag repo.

If you started developing can you let me know? Otherwise I might try to do it.

**Comment by kbs1** [comment]
Hi Guys,

what do you mean by this feature? Pick nodes from whitelist (which have open ports), and display them on the website? Where? An performance, you mean luck factor?

@xrdavies

**Comment by xrdavies** [comment]
@kbs1  As I think, it's round robin query, just like a poll, fetch status of each pool listed in white-list every 30 mins or longer.

**Comment by cnukaus** [comment]
Currently the website employs some method to read a "report" such as
state.txt file from each pool, the state.txt file can be out-of-date, just
shows website is alive. And the proposed feature will do a actual probe to
the port and test the service is alive.

**Comment by kbs1** [comment]
@xrdavies so each pool should have a list of other pools somewhere on the website, based on whitelist, with status? What if the pool website doesn't run on the same IP?

@cnukaus that's correct. But there are issues again that the pool website might run on another IP than the pool, and the pool owner of another pool (that we check) might use firewall to only allow actual pools to connect to the port, and our connection attempt would fail even if the pool is up.

So we would need to write scripts in openxdagpool-scripts that check this (those scripts run on the same server / IP as the pool), and this can be exported periodically, I will do that. But it will just show which pool port is OPEN from our view, and which one is CLOSED (and won't show pool status).

Would this be enough? This listing shouldn't be available to generic users right?:)

**Comment by ghost** [comment]
@cnukaus Xdag.io reads state.txt from the different pools using CORS. 

A requirement of whitelisting is that this file should be updated with a maximum of 1 minute intervals, and as such, we can assume that the data is not out of date. If the pool is offline, it will return "State: Offline". If the state cannot be resolved, it returns "State could not be resolved."

This list is for miners. Xdag.io only shows pools that donate at least 1% to the community fund, and will continue to do so.

**Comment by kbs1** [comment]
Yes, that description is correct. @mathsw I am writing a totally new version of OpenXDAGPool-scripts, that will export pool stats in nice JSON rather than just a text file (every minute also). It also includes a lot of diagnostic information about the pool, together with date of export (!). So it will be fully suitable. Sorry for changing the API, but this should be the final "stats export" version. It will be ready this week / weekend.

**Comment by ghost** [comment]
@kbs1 That would be rather nice, looking forward to this update.

**Comment by cnukaus** [comment]
@mathsw the requirement of 1 minute interval is good, however it's not
enforced or validated. When I think about a "checking" mechanism, it suit
the scenario that there are lot's of pools and it is worthwhile to maintain
a database to accumulate historical status of each pool...

@kbs1 JSON format is nice as easy to store a timestamp as self-declaration.

**Comment by kbs1** [comment]
@xrdavies @cnukaus @mathsw the new release is ready, stats are now available at each openxdagpool at /status (JSON) and /status/human-readable (text file). This information is updated once every minute.

**Comment by xrdavies** [comment]
@kbs1  Great work!!
Thank you so much!

**Comment by mot2017** [comment]
@xrdavies   I want to know you and exchange XDAGPOOL to build，Can you provide your WeChat？
