### ISSUE TITLE
error running "npm run production"

### ISSUE THREAD

**Issue by felix920506** [XDagger/openxdagpool#3]
Logs here:
[2018-06-06T13_33_41_290Z-debug.log](https://github.com/XDagger/openxdagpool/files/2076495/2018-06-06T13_33_41_290Z-debug.log)
Ubuntu 16.04.4 LTS

**Comment by kbs1** [comment]
Hi, please post `npm install` output after `rm -fr node_modules package-lock.json` in openxdagpool folder.

**Comment by mrsaicharan1** [comment]
@felix920506 How were you able to fix the  error? **npm run production** still produces the sam error.

**Comment by kbs1** [comment]
Please post me the output of fresh `npm install`, e.g. remove node_modules and run npm install. Does it end successfully?

**Comment by mrsaicharan1** [comment]
Yeah, just followed whatever you mentioned. Putting up the logs. it has two errors.

**Comment by felix920506** [comment]
I just reformatted the system and started over again.
This is the trick I use :
When I complete each step, I shut down the machine and stick the hard drive
onto my dual bay external hard drive enclosure which happens to have a
feature of cloning hard drives. I just clone the hard drive over to another
one then continue. I’ve avoided redoing previous steps by using this method
several times.

**Comment by kbs1** [comment]
Where are the logs?

**Comment by mrsaicharan1** [comment]
Just a minute...

**Comment by mrsaicharan1** [comment]
![npm-debug](https://user-images.githubusercontent.com/25197147/41418899-4f7df058-6fe0-11e8-9005-50cb8e1765b1.jpeg)

**Comment by mrsaicharan1** [comment]
I'm using a vps btw

**Comment by kbs1** [comment]
That looks like npm run production. Please post npm install as I described. Can you post it as a text file? (over ssh?)

**Comment by mrsaicharan1** [comment]
Yeah . will send now.

**Comment by mrsaicharan1** [comment]
Actually , there were no errors. Only warnings. Nothing in npm-debug.log

**Comment by mrsaicharan1** [comment]
Do you require the dependency tree which was installed

**Comment by kbs1** [comment]
So when npm install completed successfully, doesn't npm run production still work?

**Comment by kbs1** [comment]
It is required by installed packages

**Comment by kbs1** [comment]
Anyway post the npm install output. npm-debug.log is not necessary right now.

**Comment by mrsaicharan1** [comment]
No it still gives the same error  

>  Error: @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`

**Comment by kbs1** [comment]
just remove node_modules and post npm install output

**Comment by kbs1** [comment]
Also your npm and node seem to be ancient. It is mentioned in readme to install newer vesions, this may be the cause.

**Comment by mrsaicharan1** [comment]
Yes will try updating maybe. I did update once but will try again.

**Comment by mrsaicharan1** [comment]
Compiled successfully. Ran production. Uninstalled and Installed again 2-3 times and updated. Thanks! @kbs1

**Comment by mrsaicharan1** [comment]
Now i'm getting the error mentioned in the issue. :P

**Comment by kbs1** [comment]
Which error? Or is it working for you now?
