### ISSUE TITLE
artisan - Unable to call openxdagpool-scripts core.

### ISSUE THREAD

**Issue by felix920506** [XDagger/openxdagpool#4]
When I run "php artisan data:live" I hit an issue:

In Core.php line 30:
Unable to call openxdagpool-scripts core

**Comment by kbs1** [comment]
Hi, do you have the .env file settings correct? Can you call the core manually using wget?

**Comment by felix920506** [comment]
Where is the core stored?
What command should I type?

**Comment by kbs1** [comment]
Hi, please see detailed instructions here: https://github.com/XDagger/openxdagpool-scripts

**Comment by mrsaicharan1** [comment]
I've followed the instructions given in the openxdagpool-scripts repo. The scripts are running. But I still get the error. Unable to understand what's going on
`In Core.php line 30:
Unable to call openxdagpool-scripts core`

**Comment by kbs1** [comment]
can you call the core using wget?

**Comment by mrsaicharan1** [comment]
Will try and get back to you asap.

**Comment by mrsaicharan1** [comment]
Wait, what do you mean by calling it using wget? wget is used for downloading from urls, isn't it?

**Comment by kbs1** [comment]
I've updated the readme with detailed steps, please see it :)
