### ISSUE TITLE
Hello, can you have a Chinese step tutorial?

### ISSUE THREAD

**Issue by lazy1523** [XDagger/openxdagpool#5]
Hello, can you give me a Chinese step tutorial?

**Comment by kbs1** [comment]
Hi, if you can translate the current tutorial, then yes ;-) But internationalization is not ready in app (no support), but it's a good first step :)

**Comment by lazy1523** [comment]
Can you do a detailed step? Starting with the new Ubuntu 16.04  tanks you；）

**Comment by kbs1** [comment]
I can't, because I don't speak that language. If you want, you can translate it, then I can use your translation in the code repository. Thank you :)
